import { CrosshairSettingsObj } from "./types";

export const crosshairPresets: CrosshairSettingsObj[] = [
  {
    dotOpacity: 0,
    dotOutlineOpacity: 0,
    pipBorder: false,
    pipGap: 1,
    pipHeight: 18,
    pipOpacity: 1,
    pipWidth: 3,
    colorR: 255,
    colorG: 255,
    colorB: 255,
    defaultPipGap: 10,
  },
  {
    dotOpacity: 0.5,
    dotOutlineOpacity: 0.8,
    pipBorder: true,
    pipGap: 2,
    pipHeight: 20,
    pipOpacity: 0.9,
    pipWidth: 4,
    colorR: 0,
    colorG: 255,
    colorB: 0,
    defaultPipGap: 10,
  },
  {
    dotOpacity: 1,
    dotOutlineOpacity: 0.5,
    pipBorder: false,
    pipGap: 3,
    pipHeight: 15,
    pipOpacity: 0.7,
    pipWidth: 5,
    colorR: 255,
    colorG: 0,
    colorB: 0,
    defaultPipGap: 10,
  },
  {
    dotOpacity: 0.3,
    dotOutlineOpacity: 1,
    pipBorder: true,
    pipGap: 4,
    pipHeight: 25,
    pipOpacity: 1,
    pipWidth: 2,
    colorR: 0,
    colorG: 0,
    colorB: 255,
    defaultPipGap: 10,
  },
  {
    dotOpacity: 0.7,
    dotOutlineOpacity: 0.2,
    pipBorder: false,
    pipGap: 2,
    pipHeight: 22,
    pipOpacity: 0.8,
    pipWidth: 6,
    colorR: 255,
    colorG: 165,
    colorB: 0,
    defaultPipGap: 10,
  },
  {
    dotOpacity: 0.7,
    dotOutlineOpacity: 0.6,
    pipBorder: false,
    pipGap: 3,
    pipHeight: 25,
    pipOpacity: 1,
    pipWidth: 5,
    colorR: 255,
    colorG: 165,
    colorB: 0,
    defaultPipGap: 10,
  },
];
